=== BackupTheBerlios/wanduxteam/wandux/utils/adll/linux/template/adll.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT template (netboot|section)*>
<!ATTLIST template author CDATA #IMPLIED>
<!ATTLIST template os_name CDATA #REQUIRED>
<!ATTLIST template os_version CDATA #REQUIRED>
<!ATTLIST template adll_version CDATA #REQUIRED>
<!ATTLIST template date CDATA #IMPLIED>

<!ELEMENT section (option|comment|command|section)*>
<!ATTLIST section name CDATA #REQUIRED>
<!ATTLIST section visible (yes|no) 'yes'>
<!ATTLIST section needed (yes|no) 'no'>
<!ATTLIST section label CDATA #REQUIRED>
<!ATTLIST section multi (yes|no) 'no'>
<!ATTLIST section separator CDATA #IMPLIED>

<!ELEMENT option (choice*|option*)>
<!ATTLIST option label CDATA #REQUIRED>
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST option type (combo|list|radio|check|text) 'text'>
<!ATTLIST option visible (yes|no) 'yes'>
<!ATTLIST option needed (yes|no) 'no'>
<!ATTLIST option multi (yes|no) 'no'>
<!ATTLIST option separator CDATA #IMPLIED>
<!ATTLIST option terminator CDATA #IMPLIED>

<!ELEMENT choice (#PCDATA|option)*>
<!ATTLIST choice label CDATA #IMPLIED>
<!ATTLIST choice needed (yes|no) 'no'>
<!ATTLIST choice selected (yes|no) 'no'>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT command (#PCDATA)>
<!ATTLIST command visible (yes|no) 'yes'>
<!ATTLIST command needed (yes|no) 'no'>

<!ELEMENT netboot (address,port,path)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT path (#PCDATA)>

=== BackupTheBerlios/wanduxteam/wandux/utils/adll/linux/template/xml_solaris_sysidcfg.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE template SYSTEM "adll.dtd"[]>
<template author="Vincent Malguy" os_name="Solaris" os_version="8 and 9" adll_version="1.0" date="01-11-2004">
  <netboot>
    <address>192.1.1.150</address>
    <port>21</port>
    <path>/path</path>
  </netboot>

<section label="Network" name="">
<comment>Name service, domain name, name server. Options for NIS and NIS+: {domain_name=domain_name name_server=hostname(ip_address)} . Options for DNS: {domain_name=domain_name name_server=ip_address,ip_address, ip_address (three maximum) search=domain_name,domain_name,domain_name,domain_name,domain_name, domain_name (six maximum, total length less than or equal to 250 characters)}. Options for LDAP: {domain_name=domain_name profile=profile_name profile_server=ip_address proxy_dn="proxy_bind_dn" proxy_password=password}</comment>
<option label="Name service" name="name_service" type="radio">
<choice label="NIS">=NIS</choice>
<choice label="NIS+">=NIS+</choice>
<choice label="LDAP">=LDAP</choice>
<choice label="DNS">=DNS</choice>
</option>
<option label="Option for name service" name="" type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>
<comment>Network interface, host name, Internet Protocol (IP) address, netmask, DHCP, IPv6. NONE turns off networking. PRIMARY is the first up, nonloopback interface that is found on the system. The order is the same as with "ifconfig." If no interfaces are up, then the first nonloopback interface is used. If no nonloopback interfaces are found, then the system is set to NON-NETWORKED.</comment>
<option label="Network interface" name="network_interface" type="radio">
<choice label="NONE">=NONE</choice>
<choice label="PRIMARY">=PRIMARY</choice>
<choice label="Manuel option below"></choice>
</option>
<comment>If DHCP is to be used, specify: {dhcp protocol_ipv6=yes_or_no}.  
If DHCP is not to be used, specify: {hostname=host_name default_route=ip_address or NONE ip_address=ip_address netmask=netmask protocol_ipv6=yes_or_no}</comment>
<option label="Option for Network Interface" name=" " type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
</section>
<section label="Security" name="">
<option label="Root password" name="root_password=" type="text" terminator="&#xD;&#xA;">
<choice label=" " > </choice>
</option>
<option label="Security policy" name="security_policy" type="radio">
<choice label="Kerberos">=kerberos</choice>
<choice label="None">=NONE</choice>
</option>
<comment>Options for Kerberos: {default_realm=FQDN admin_server=FQDN kdc=FQDN1, FQDN2, FQDN3}
(FQDN is a fully qualified domain name.)</comment>
<option label="Option for Kerberos" name=" " type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
</section>
<section label="Local configuration" name="">
<comment>The /usr/lib/locale directory or Appendix D, Locale Values (Reference) provides the valid locale values.</comment>
<option label="Language in which to display the install program and desktop" name="system_locale=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>The subdirectories in the /usr/share/lib/terminfo directory provide the valid terminal values.</comment>
<option label="Terminal type" name="terminal=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>The directories and files in the /usr/share/lib/zoneinfo directory provide the valid time zone values. The time zone value is the name of the path relative to the /usr/share/lib/zoneinfo directory. For example, the time zone value for mountain standard time in the United States is US/Mountain. The time zone value for Japan is Japan. You can also specify any valid Olson time zone.</comment>
<option label="Time zone" name="timezone=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>If you specify localhost as the time server, the system's time is assumed to be correct. If you are not running a name service and you specify the hostname or ip_addr of a system, that system's time is used to set the time.</comment>
<option label="Date and time Server" name="timeserver=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>On the system you want to install, run kdmconfig -d filename. Append output to sysidcfg file.</comment>
<option label="x86: Monitor type" name="monitor=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>On the system you want to install, run kdmconfig -d filename. Append output to sysidcfg file.</comment>
<option label="x86: Keyboard language, keyboard layout" name="keyboard=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>On the system you want to install, run kdmconfig -d filename. Append output to sysidcfg file.</comment>
<option label="x86: Graphics card, screen size, color depth, display resolution" name="display=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
<comment>On the system you want to install, run kdmconfig -d filename. Append output to sysidcfg file.</comment>
<option label="x86: Pointing device, number of buttons, IRQ level" name="pointer=" type="text" terminator="&#xD;&#xA;">
<choice label=" "></choice>
</option>
</section>
</template>

=== BackupTheBerlios/wanduxteam/wandux/utils/adll/linux/template/xml_solaris_8_profil.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE template SYSTEM "adll.dtd"[]>
<template author="Vincent Malguy" os_name="Solaris" os_version="8 and 9 profil file" adll_version="1.0" date="01-11-2004">
  <netboot>
    <address>192.1.1.150</address>
    <port>21</port>
    <path>/path</path>
  </netboot>

<section label="Disk configuration" name="">
<comment>boot_device designates the device where the JumpStart program is to install the root (/) file system and the system's boot device. </comment>
<option label="Root Location " name="boot_device " type="radio">
<choice label="existing">existing</choice>
<choice label="any" selected="yes">any</choice>
<choice label="enter custom below"> </choice>
</option>
<option label="custom device" name="" type="text" terminator=" preserve &#xD;&#xA;">
<choice label=""></choice> 
</option>

<comment>bootenv createbe enables you to create an empty-and-inactive boot environment at the same time you are installing the operating environment.</comment>
<option label="custom device" name="bootenv createbe bename " type="text">
<choice label=""></choice>
</option>
<option label="on filesystem" name=" filesystem " type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>

<comment>dontuse designates one or more disks that you do not want the JumpStart program to use. </comment>
<option label="Disk not to use " name="dontuse " type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>

<comment>fdisk defines how the fdisk partitions are set up on an x86 based system. </comment>
<option label="fdisk actions" name="fdisk " type="radio">
<choice label="all">all</choice>
<choice label="rootdisk">rootdisk</choice>
<choice label="custom enter below"> </choice>
</option>
<option label="Enter custom disk to fdisk " name=" " type="text">
<choice label=""></choice>
</option>
<option label="Partition type" name=" " type="radio">
<choice label="solaris standard">solaris</choice>
<choice label="Dos">dosprimary</choice>
</option>
<option label="Size of the partition" name=" " type="radio" >
<choice label="All space available (delete existing partition)">all</choice>
<choice label="Maximun free space (preserve existing partition)">maxfree</choice>
<choice label="custom enter below"> </choice>
</option>
<option label="Enter  size in Mbytes" name=" " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>


<comment>By using filesys with the listed values, the JumpStart program sets up the installed system to automatically mount remote file systems when the system boots.</comment>
<option label="Mounting Remote File Systems A MULTIPLIER" name="filesys " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>


<comment>The metadb keyword enables you to create Solaris Volume Manager state database replicas (metadbs) during your custom JumpStart installation.</comment>
<option label="Locale AMULTIPLIER" name="metadb " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>



 
<comment>partitioning defines how the disks are divided into slices for file systems during the installation.</comment>
<option label="Enter the type of partitioning you want" name="partitioning " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>

<comment>Choose a custom root device slice.</comment>
<option label="Enter the root device slice " name="root_device " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>


<comment> The usedisk profile keyword designates one or more disks that you want the JumpStart program to use. You must specify disk_name in the form cxtydz or cydz, for example, c0t0d0 or c0d0s0.</comment>
<option label="Enter the disk you want to use " name="usedisk " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>


</section>

<section label="Locale configuration" name="">
<comment>geo designates the regional locale or locales that you want to install . </comment>
<option label="Locale " name="geo " type="radio" terminator="&#xD;&#xA;">
<choice label="Northern Africa, including Egypt">N_Africa</choice>
<choice label="Central America, including Costa Rica, El Salvador, Guatemala, Mexico, Nicaragua, Panama">C_America</choice>
<choice label="North America, including Canada, United States">N_America</choice>
<choice label="South America, including Argentina, Bolivia, Brazil, Chile, Colombia, Ecuador, Paraguay, Peru, Uruguay, Venezuela">S_America</choice>
<choice label="Asia, including Japan, Republic of Korea, People's Republic of China, Taiwan, Thailand">Asia</choice>
<choice label="Australasia, including Australia, New Zealand">Ausi</choice>
<choice label="Central Europe, including Austria, Czech Republic, Germany, Hungary, Poland, Slovakia, Switzerland">C_Europe</choice>
<choice label="Eastern Europe, including Albania, Bosnia, Bulgaria, Croatia, Estonia, Latvia, Lithuania, Macedonia, Romania, Russia, Serbia, Slovenia, Turkey">E_Europe</choice>
<choice label="Northern Europe, including Denmark, Finland, Iceland, Norway, Sweden">N_Europe</choice>
<choice label="Southern Europe, including Greece, Italy, Portugal, Spain">S_Europe</choice>
<choice label="Western Europe, including Belgium, France, Great Britain, Ireland, Netherlands">W_Europe</choice>
<choice label="Middle East, including Israel">M_East</choice>
</option>

<comment>locale designates the locale packages you want to install or add when upgrading for the specified locale_name.</comment>
<option label="Locale " name="locale " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>



</section>

<section label="Software configuration" name="">
<comment>cluster designates the software group to add to the system</comment>
<option label="Cluster to install" name="cluster " type="check">
<choice label="Core System Support Software Group">SUNWCreq </choice>
<choice label="End User Solaris Software Group">SUNWCuser </choice>
<choice label="Developer Solaris Software Group">SUNWCprog </choice>
<choice label="Entire Solaris Software Group">SUNWCall </choice>
<choice label="Entire Solaris Software Group Plus OEM Support">SUNWCXall </choice>
</option>
<option label="on filesystem" name=" filesystem " type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>


<comment>package designates whether a package is to be added to or deleted from the software group that is to be installed on the system. syntax : package_name [add [retrieval_type location]| delete]</comment>
<option label="Enter the name of the package to install" name="package " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>


<comment>add a patch during installation . syntax : patch_id_list | patch_file patch_location optional_keywords]</comment>
<option label="Enter the name of the patch " name="patch " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>



</section>

<section label="Diskless client configuration" name="">


<comment>num_clients defines the number of diskless clients, client_num, that a server supports.</comment>
<option label="Number of diskless client" name="num_client " type="text" terminator="&#xD;&#xA;">
<choice label=""> </choice>
</option>

<comment>client_arch specifies that the operating system server is to support a different platform group than the server uses. </comment>
<option label="Client Architecture " name="client_arch " type="radio" terminator="&#xD;&#xA;">
<choice label="sun4m">sun4m</choice>
<choice label="sun4u">sun4u</choice>
<choice label="i86pc" selected="yes">i86pc</choice>
</option>
<comment>client_root defines the amount of root space, root_size in Mbytes, to allocate for each client.</comment>
<option label="client root " name="client_root " type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>

<comment>client_swap defines the amount of swap space, swap_size in Mbytes, to allocate for each diskless client.</comment>
<option label="client swap " name="client_swap " type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>
</section>

<section label="Architecture configuration" name="">
<comment>system_type defines the type of system on which the Solaris OS is to be installed.</comment>
<option label="Choose if system is standalone or a server" name="system_type " type="radio" terminator="&#xD;&#xA;">
<choice label="standalone">standalone</choice>
<choice label="server">server</choice>
</option>

</section>



<section label="File Location A METTRE EN DUR ?" name="">
<comment>Set the location where the Solaris Flash archive is stored. </comment>
<option label="archive location " name="archive_location " type="radio">
<choice label="NFS serer"> </choice>
<choice label="HTTP or HTTPS Server"> </choice>
<choice label="FTP Server"> </choice>
<choice label="Local Tape"> </choice>
<choice label="Local Device"> </choice>
<choice label="Local File"> </choice>
</option>
<option label="Location" name="" type="text" terminator="&#xD;&#xA;">
<choice label=""></choice>
</option>
</section>



</template>
